version: '3'

services:
  chat:
    image: joao29a/chat-delicioso:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "9000:8000"
    networks:
      - safadeza

  redis:
    container_name: tech-redis
    image: redis
    ports:
      - "9090:6379"
    networks:
      - safadeza

networks:
  safadeza: